name: Automated API tests using Newman CLI

on: push

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Newman and Allure commandline
        run: |
          npm install -g newman
          npm install -g allure-commandline

      - name: Run API tests and generate Allure results
        run: |
          newman run "${{ github.workspace }}/Postman Collections/testCiCd.json" -e "30389425-d4690b22-5e33-4b0e-ba23-894a45cea9db" --reporters cli,allure --reporter-allure-export allure-results

      - name: Generate Allure Report
        run: |
          allure generate allure-results --clean -o allure-report

      - name: Deploy Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: allure-report